### PR TITLE
Use a different style name for each prompt

### PR DESCRIPTION
**Pull request by jongiddy**
This fixes a problem on Chrome and Safari (https://github.com/sbrunner/sphinx-prompt/issues/2), which do not support scoped styles, where multiple prompt directives with different prompts display the same prompt for each content section.

### CODE REVIEW

**Comment by adamtheturtle** [comment]
Thanks @jongiddy.

Tested by viewing http://build.clusterhq.com/results/docs/sphinx-prompt-FLOC-1548/build-7547/using/installing/index.html on OS X 10.10.3 in Safari 8.0.6, Firefox 38.01 and Chrome 43. Unfortunately it showed up some bad prompts! I'll deal with that separately.

Hopefully the patch will be accepted soon. Address the minor comments and merge when you and the docs builder are happy.

**Comment by sbrunner** [comment]
Thanks @jongiddy for your contribution :-)

**Comment by jongiddy** [comment]
Thanks for your quick response. Any idea when an updated version will be available in PyPI?

**Comment by sbrunner** [comment]
Probably next week :-)

**Comment by jongiddy** [comment]
Thanks. Note, this should allow you to close issue #2

**Comment by sbrunner** [comment]
Effectively thanks :-)

**Comment by sbrunner** [comment]
Done :-)

**Pull request merged**
